version: "3.9"

networks:
  default:

services:
  node:
    image: terraformlabs/cosmovisor:${COMPOSE_PROJECT_NAME}-edge
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      args:
        CHAIN_NAME: ${CHAIN_NAME}
        CHAIN_DIR: ${COMPOSE_PROJECT_NAME}
    env_file:
      - chains/${COMPOSE_PROJECT_NAME}/.env
    volumes:
      - /app
    networks:
      - default
